apiVersion: batch/v1
kind: CronJob
metadata:
  name: hello
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: hello
            image: maxsanders/db:latest
            imagePullPolicy: IfNotPresent
          restartPolicy: Never